server: #端口号配置
  port: 8889
spring:
  datasource: #jdbc配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crk_new?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8
    username: root
    password: root
    platform: mysql
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
mybatis-plus:
#  check-config-location: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.unis.crk.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: not_null
#自定义配置
project:
  uncurbed:
    url: /login
    role: ROLE_LOGIN